### ISSUE TITLE
Bug - Site crashes after user searches property

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#1043]
**Describe the bug**
When a user looks up a property and then clicks a link in the navbar, the web application crashes and shows a client-side error screen.

```
2117-e0c701d8057c2152.js:1 TypeError: Cannot read properties of undefined (reading 'getSource')
    at rx.getSource (05f6971a-22d488b7be83c68e.js:51:205574)
    at y (8556-344b47f3e82064cf.js:2:30526)
    at Object.setMarkers (8556-344b47f3e82064cf.js:2:31112)
    at n (8556-344b47f3e82064cf.js:2:72895)
    at f (8556-344b47f3e82064cf.js:2:32930)
    at Array.forEach (<anonymous>)
    at p (8556-344b47f3e82064cf.js:2:32990)
    at Q (8556-344b47f3e82064cf.js:2:35375)
    at eX.$destroy (8556-344b47f3e82064cf.js:2:36356)
    at push.94205.n.current.e.<computed>.n.current.$set (
```

**To Reproduce**

1. Go to https://cleanandgreenphilly.org/find-properties/884341730
2. Click on any link in navbar
3. See error

**Expected behavior**
When user clicks a navbar link, it should take them to the correct page without crashing.

**Screen recording**

https://github.com/user-attachments/assets/c198b6a2-56bf-4623-8576-a4f04e19ab7e

**Screenshots**
Error screen
<img width="1268" alt="Screen Shot 2024-12-10 at 7 05 03 PM" src="https://github.com/user-attachments/assets/b5e27e7f-ef74-4ac5-ada4-7aee3f09eacf">

Error message in browser console
<img width="600" alt="Screen Shot 2024-12-10 at 7 05 19 PM" src="https://github.com/user-attachments/assets/afc7fe15-2061-4c90-a529-5e6ebdfd0254">

**Desktop (please complete the following information):**

- OS: MacOS Monterey v12.7.6
- Browser Chrome
- Version 131.0.6778.109

**Additional context**
Reported by @brandonfcohen1 on Clean & Green Philly's Slack channel

**Comment by CodeWritingCow** [comment]
In production env (AKA the live website), I used a debugger in Google Chrome's DevTools to see what `getSource` is doing.

When user first navigates to find-properties page, getSource() is passed `vacant-properties-tiles` as the argument:

![Screen Shot 2024-12-10 at 9 17 25 PM](https://github.com/user-attachments/assets/f3f43c86-0fd9-4b62-a908-839411b025a8)

As the find-properties page loads, getSource() is passed `full-geom` as the argument:

![Screen Shot 2024-12-10 at 9 19 08 PM](https://github.com/user-attachments/assets/8ffc234b-83d2-4bc6-8c03-e20ea51faa9e)

Finally, user goes to get-access page. As the page loads (and before it crashes), getSource() is passed `full-geom` as the argument:

![Screen Shot 2024-12-10 at 9 21 07 PM](https://github.com/user-attachments/assets/ce69ef35-3d8d-4f7b-9019-8163c4134e02)

Perhaps this is related to the bug. It could also be a red herring.

**Comment by CodeWritingCow** [comment]
So the bug is caused by changes to Mapbox in PRs #1003 and #1008. I confirmed this by visiting the Vercel preview env for PR 1003 at https://vacant-lots-proj-13xrykfdy-clean-and-green-philly.vercel.app/

I also visited the Vercel preview envs for other front-end PRs submitted around the same time as PR 1003. The error did not occur in the Vercel preview envs for those PRs:

- https://github.com/CodeForPhilly/clean-and-green-philly/pull/989
- https://github.com/CodeForPhilly/clean-and-green-philly/pull/999

The solution is to revert PRs 1003 and 1008. I tested this in my local env, and the error was not happening locally.


## Screen recording
Here is a video recording of the error happening in Vercel preview env for 1003:

https://github.com/user-attachments/assets/7ea0cba9-e0b0-4fa4-99db-700b2c3a504c
