### ISSUE TITLE
Bug - Invalid ARIA attribute ariaCurrent

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#1048]
**Describe the bug**
The website is printing a console warning: `Invalid ARIA attribute `ariaCurrent`. Did you mean 'aria-current'`.

```
Warning: Invalid ARIA attribute `ariaCurrent`. Did you mean `aria-current`?
    at a
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/link/dist/chunk-FGDGYNYV.mjs:19:86)
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/button/dist/chunk-DBLREEYE.mjs:20:188)
    at Lazy
    at div
    at div
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at div
    at main
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:347:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:153:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:228:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at Lazy
    at FilterProvider (webpack-internal:///(ssr)/./src/context/FilterContext.tsx:42:27)
    at FilterProviderWrapper (webpack-internal:///(ssr)/./src/app/FilterProviderWrapper.tsx:10:34)
    at Lazy
    at CookieProvider (webpack-internal:///(ssr)/./src/context/CookieContext.tsx:21:27)
    at CookieProviderWrapper (webpack-internal:///(ssr)/./src/app/CookieProviderWrapper.tsx:10:34)
    at Lazy
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:322:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:202:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:112:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:158:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:564:13)
    at Lazy
    at r6 (/Users/garypang/Documents/GitHub/code-for-philly/vacant-lots-proj/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:19018)
    at r6 (/Users/garypang/Documents/GitHub/code-for-philly/vacant-lots-proj/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:19018)
    at ServerInsertedHTMLProvider (/Users/garypang/Documents/GitHub/code-for-philly/vacant-lots-proj/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:24765)
```

**To Reproduce**

1. Run the web application on `main` branch in local environment
2. Open Web browser DevTools' console window
3. See error

**Expected behavior**
The error message should not appear.

**Screenshots**
![Screen Shot 2024-12-11 at 3 18 06 AM](https://github.com/user-attachments/assets/ffc47b61-96a1-4de9-b1b9-beb4f92ca9f9)

**Desktop:**

- OS: MacOS Monterey v12.7.6
- Browser Chrome
- Version 131.0.6778.109

**Comment by DonovanAndrews300** [comment]
I would like to tackle this bug!

**Comment by bacitracin** [comment]
Assigned!
